version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      DB_NAME: gdp_data
      DB_USER: cloudwalk
      DB_PASSWORD: EzOiDSqfrdy5cbkXhr2LQHN6eB1SzE3O
      DB_HOST: dpg-cp4lc5779t8c73ei01pg-a.oregon-postgres.render.com
      DB_PORT: 5432
    command: ["./run.sh"]

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - app
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/setup_pgadmin.sh:/docker-entrypoint-initdb.d/setup_pgadmin.sh
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
