version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gdp_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "python scripts/extract.py &&
               python scripts/load.py &&
               psql -h db -U postgres -d gdp_data -f scripts/transform.sql"
    environment:
      PGPASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
