version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gdp_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - db

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["./run.sh"]
    environment:
      PGPASSWORD: postgres
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/setup_pgadmin.sh:/docker-entrypoint-initdb.d/setup_pgadmin.sh
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local
